from dataclasses import dataclass


@dataclass
class ButtonText:
    ru = 'Русский'
    en = 'English'

    joined = 'Участник'
    kicked = 'Покинул'
    blocked = 'Заблокирован'
    add = 'Добавить'
    delete = '×'
    hide = '×'
    delete_t = 'Удалить'
    list = 'Список'
    confirm = 'Подтвердить'
    back = '⇽'
    next = '⇾'
    next_t = 'Далее ›'
    back_t = '‹ Назад'
    reload = '↻'
    stop = '■'
    search = '⌕'
    clean = 'Очистить'
    first_page = '« {first_page}'
    prev_page = '‹ {prev_page}'
    curr_page = '·{curr_page}·'
    next_page = '{next_page} ›'
    last_page = '{last_page} »'

    admins = 'Администраторы'
    users = 'Пользователи'
    messages = 'Сообщения'
    buttons = 'Кнопки'
    newsletter = 'Рассылка'
    sponsorship = 'Спонсорка'

    # -----sponsorship
    sponsorship_active_t = 'Спонсируется'
    sponsorship_active = 'Спонсировать'
    sponsorship_inactive_t = 'Не спонсируется'
    sponsorship_inactive = 'Не спонсировать'
    sponsorship_edit_chat_id = 'Изменить чат ID'
    sponsorship_edit_chat_title = 'Изменить название'
    # -----newsletter
    create = 'Создать'
    postponed = 'Отложенные'
    add_buttons = 'Добавить кнопки'
    del_buttons = 'Удалить кнопки'
    run = 'Запустить'
    postpone = 'Отложить'
    in_ru = 'На русском'
    in_en = 'На английском'
    send_all = 'Разослать всем'
    del_post = 'Удалить пост'
    edit_time = 'Изменить время'
    # -----admins
    admin = 'Администратор'
    moder = 'Модератор'
    switch_to_moder = 'Понизить до модератора'
    switch_to_admin = 'Повысить до администратора'
    switch_to_user = 'Понизить до участника'
    edit_name = 'Изменить имя'
    edit_id = 'Изменить ID'
    # -----admins
    block = 'Заблокировать'
    unblock = 'Раблокировать'
    send_message = 'Написать сообщение'
    reply_message = 'Ответить'
